language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

sudo: enabled

install:
  - pip install -r recipes-generator/requirements.txt

before_script:
  - cd recipes-generator

script:
  - make validate
  - make test
